#不同项目在不同环境下的域名，其中"defalut"用于控制默认环境
test:
  codemao_app_api_host: https://test-gateway.codemao.cn/codemao-app-web
  admin_api_host: https://test-codecamp-teaching-system.codemao.cn
  account_api_host: https://test-api.codemao.cn
staging:
  codemao_app_api_host: https://staging-gateway.codemao.cn/codemao-app-web
  admin_api_host: https://staging-codecamp-teaching-system.codemao.cn
  account_api_host: https://staging-api.codemao.cn
prod:
  codemao_app_api_host: https://gateway.codemao.cn/codemao-app-web
  admin_api_host: https://codecamp-teaching-system.codemao.cn
  account_api_host: https://api.codemao.cn


dafalut: test
